// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArhlkARxVor9DySBWMfwRG1FRQDUy6_dA',
    appId: '1:866440291504:web:1e7ece56f427dd56328775',
    messagingSenderId: '866440291504',
    projectId: 'newsnet-8a184',
    authDomain: 'newsnet-8a184.firebaseapp.com',
    storageBucket: 'newsnet-8a184.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArhlkARxVor9DySBWMfwRG1FRQDUy6_dA',
    appId: '1:866440291504:android:1e7ece56f427dd56328775',
    messagingSenderId: '866440291504',
    projectId: 'newsnet-8a184',
    storageBucket: 'newsnet-8a184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArhlkARxVor9DySBWMfwRG1FRQDUy6_dA',
    appId: '1:866440291504:ios:1e7ece56f427dd56328775',
    messagingSenderId: '866440291504',
    projectId: 'newsnet-8a184',
    storageBucket: 'newsnet-8a184.firebasestorage.app',
    iosClientId: '866440291504-al4c2oka73c0bm32n28kue9pdgbtjhib.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArhlkARxVor9DySBWMfwRG1FRQDUy6_dA',
    appId: '1:866440291504:ios:1e7ece56f427dd56328775',
    messagingSenderId: '866440291504',
    projectId: 'newsnet-8a184',
    storageBucket: 'newsnet-8a184.firebasestorage.app',
    iosClientId: '866440291504-al4c2oka73c0bm32n28kue9pdgbtjhib.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsnet',
  );
} 